name: M3U Guncelleme
on:
  schedule:
    - cron: '0 * * * *' # Her saat başı çalışır
  workflow_dispatch: # İstediğinde butona basıp çalıştırmanı sağlar

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Çek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kütüphaneleri Kur
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Linki Yakala
        run: python main.py

      - name: GitHub'a Geri Yükle
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # Sadece dosya varsa işlem yap, yoksa hata verme
          if [ -f live.m3u ]; then
            git add live.m3u
            git commit -m "Yayin Linki Guncellendi"
            git push
          else
            echo "live.m3u bulunamadi, commit atlaniyor."
          fi
